[project]
name = 'microtask-dao-clarity'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.config]
path = 'contracts/config.clar'
clarity_version = 3
epoch = 3.1

[contracts.disputes]
path = 'contracts/disputes.clar'
clarity_version = 3
epoch = 3.1

[contracts.engagements]
path = 'contracts/engagements.clar'
clarity_version = 3
epoch = 3.1

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.juror_pool]
path = 'contracts/juror_pool.clar'
clarity_version = 3
epoch = 3.1

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation]
path = 'contracts/reputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.utils]
path = 'contracts/utils.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
